url: https://kiio.github.io/musings-writings
title: Jihong Lee
subtitle: Hi!
# google_custom_search: 010245880960712892902:tnjd4ryb3ci
# google_analytics_tracking_id: UA-12450662-3
permalink: /blog/:year/:month/:day/:title/
baseurl: "/musings-writings" # the subpath of your site, e.g. /blog/
instagram_username: jihongeee
github_username: jihong-lee

exclude: ["vendor", "LICENSE", "_posts/LICENSE"]

plugins: ["jekyll-lunr-js-search", "jekyll-redirect-from", "jekyll-paginate"]
lunr_search:
  js_dir: "javascripts"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

paginate: 10
paginate_path: "/blog/:num/"

recent_posts: 5
excerpt_link: "Read On —"
titlecase: true
category_dir: blog/categories

authors:
  jihong:
    name: Jihong Lee
    github: jihong-lee
    instagram: jihongeee

series:
  - title: "React Native at Artsy"
    url: series/react-native-at-artsy/
  - title: "JavaScriptures"
    url: series/javascriptures/
  - title: "Stages of Professional Growth"
    url: series/stages-of-professional-growth/
  - title: "Artsy Tech Stack"
    url: series/artsy-tech-stack/
  - title: "Open Source by Default"
    url: series/open-source-by-default/

project:
  - title: Eigen
    svg: "_includes/svg/eigen.svg"
    description:
      "The Artsy iOS app: the Art World in Your Pocket. Hundreds of thousands of downloads. A reference for
      building large-scale Cocoa applications. Built as a hybrid native-web mix, now with React Native."
    category: featured
    link: artsy/eigen
    repository: https://github.com/artsy/eigen
    created: Nov 18th, 2012